#!/bin/sh
#make python3
#echo "Enter py Name:\c"
#read fname
touch "$1"".py"
chmod +x "$1"".py"
echo "#!/usr/bin/python3" > "$1"".py"
#echo " " >> "$1"".py"

nvim "$1"".py" ||vim "$1"".py" || nano "$1"".py"
